export type CapabilityStatus =
  | "verified-official-docs"
  | "verified-existing-live-project"
  | "verified-current-live-tenant"
  | "pending-verification";

export interface ApiCapability {
  entity: string;
  operation: string;
  method: "GET" | "POST";
  pathTemplate: string | null;
  stage0Allowed: boolean;
  status: CapabilityStatus;
  evidence: string;
  liveVerifiedAt?: string;
}

const SWAGGER = "https://api.striven.com/swagger/v1/swagger.json";

export const PHASE1_CAPABILITIES: readonly ApiCapability[] = [
  {
    entity: "Customers",
    operation: "Get by ID",
    method: "GET",
    pathTemplate: "/v1/customers/{customerId}",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
  },
  {
    entity: "Customers",
    operation: "Search",
    method: "POST",
    pathTemplate: "/v1/customers/search",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
  },
  {
    entity: "Customers",
    operation: "Get contacts",
    method: "GET",
    pathTemplate: "/v1/customers/{customerId}/contacts",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
  },
  {
    entity: "Customers",
    operation: "Get locations",
    method: "GET",
    pathTemplate: "/v1/customers/{customerId}/locations",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
  },
  {
    entity: "Customers",
    operation: "Get assignments",
    method: "GET",
    pathTemplate: "/v1/customers/{customerId}/assignments",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
  },
  {
    entity: "Customers",
    operation: "Get custom-field definitions",
    method: "GET",
    pathTemplate: "/v1/customers/0/custom-fields",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
    liveVerifiedAt: "2026-09-21",
  },
  {
    entity: "Contacts",
    operation: "Get by ID",
    method: "GET",
    pathTemplate: "/v1/contacts/{contactId}",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
  },
  {
    entity: "Contacts",
    operation: "Search",
    method: "POST",
    pathTemplate: "/v1/contacts/search",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
  },
  {
    entity: "Sales Orders",
    operation: "Get by ID",
    method: "GET",
    pathTemplate: "/v1/sales-orders/{salesOrderId}",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
  },
  {
    entity: "Sales Orders",
    operation: "Search",
    method: "POST",
    pathTemplate: "/v1/sales-orders/search",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
  },
  {
    entity: "Sales Orders",
    operation: "Get assignments",
    method: "GET",
    pathTemplate: "/v1/sales-orders/{salesOrderId}/assignments",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
  },
  {
    entity: "Sales Orders",
    operation: "Get custom-field definitions",
    method: "GET",
    pathTemplate: "/v1/sales-orders/0/custom-fields",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
    liveVerifiedAt: "2026-09-21",
  },
  {
    entity: "Tasks",
    operation: "Search",
    method: "POST",
    pathTemplate: "/v1/Tasks/Search",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
  },
  {
    entity: "Tasks",
    operation: "Get by ID",
    method: "GET",
    pathTemplate: "/v1/Tasks/{TaskID}",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
  },
  {
    entity: "Tasks",
    operation: "Get types",
    method: "GET",
    pathTemplate: "/v1/Tasks/types",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
  },
  {
    entity: "Tasks",
    operation: "Get type-specific custom-field definitions",
    method: "GET",
    pathTemplate: "/v1/Tasks/types/{id}/custom-fields",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
  },
  {
    entity: "Customer Assets",
    operation: "Get by ID",
    method: "GET",
    pathTemplate: "/v1/customer-assets/{customerAssetId}",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
  },
  {
    entity: "Customer Assets",
    operation: "Search",
    method: "POST",
    pathTemplate: "/v1/customer-assets/search",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
  },
  {
    entity: "Customer Assets",
    operation: "Get asset types",
    method: "GET",
    pathTemplate: "/v1/customer-assets/types",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
    liveVerifiedAt: "2026-09-21",
  },
  {
    entity: "Customer Assets",
    operation: "Get custom-field definitions",
    method: "GET",
    pathTemplate: "/v1/customer-assets/0/custom-fields",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
    liveVerifiedAt: "2026-09-21",
  },
  {
    entity: "Customer Assets",
    operation: "Get type-specific custom-field definitions",
    method: "GET",
    pathTemplate: "/v1/customer-assets/types/{assetTypeId}/custom-fields",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
  },
  {
    entity: "Employees",
    operation: "List active",
    method: "GET",
    pathTemplate: "/v1/employees",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
    liveVerifiedAt: "2026-09-21",
  },
  {
    entity: "Employees",
    operation: "Get by ID",
    method: "GET",
    pathTemplate: "/v1/employees/{employeeId}",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
  },
  {
    entity: "Customer Locations",
    operation: "Search",
    method: "POST",
    pathTemplate: "/v1/customer-locations/search",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
  },
  {
    entity: "Items",
    operation: "Get by ID",
    method: "GET",
    pathTemplate: "/v1/items/{itemId}",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
  },
  {
    entity: "Items",
    operation: "Search",
    method: "POST",
    pathTemplate: "/v1/items/search",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
  },
  {
    entity: "Items",
    operation: "Get custom-field definitions",
    method: "GET",
    pathTemplate: "/v1/items/0/custom-fields",
    stage0Allowed: true,
    status: "verified-official-docs",
    evidence: SWAGGER,
    liveVerifiedAt: "2026-09-21",
  },
];
